# Generated by Django 5.0.3 on 2024-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_completedtest_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtest',
            name='score',
            field=models.IntegerField(),
        ),
    ]
